# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-17 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0009_auto_20190417_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstaffs',
            name='Staff_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registeredstd',
            name='Std_no',
            field=models.IntegerField(),
        ),
    ]
