# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0010_auto_20190417_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='Course_Code',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='Lect_No',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Course_Code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lect_No',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Student_No',
        ),
        migrations.RemoveField(
            model_name='registeredstaffs',
            name='Course_Code',
        ),
        migrations.RemoveField(
            model_name='registeredstd',
            name='Course_Code',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='RegisteredStaffs',
        ),
        migrations.DeleteModel(
            name='RegisteredStd',
        ),
    ]
