# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
