# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='once',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_no', models.IntegerField(max_length=100)),
            ],
        ),
    ]
